### ISSUE TITLE
Jaguar code is obsolete

### ISSUE THREAD

**Issue by lab313ru** [AmatCoder/blastem-gtk#1]
Hi,

I know, that your project is just original code plus gtk gui. But, Mike's repo doesn't have any ability to commit or help with project, so, I'm writing it here.

Blastem source contains source for the Jaguar emulation. But it is inconsistent, and cannot be compiled. Even Makefile doesn't have all needed code for that.

Maybe it will be better to remove these files from the project?

**Comment by lab313ru** [comment]
Jaguar is even not Sega's project.

**Comment by AmatCoder** [comment]
Yes, I removed the files related with Jaguar emulation. (They can be re-added later if Jaguar emulation improves)

Regards.
