### ISSUE TITLE
Can't change regions

### ISSUE THREAD

**Issue by NiBBa256** [AmatCoder/blastem-gtk#5]
The cycle mode/pal function doesn't do anything. I tried mapping it to different keys, but it doesn't work. You can force a region not only in Kega Fusion, but on the actual Megadrive.

**Comment by AmatCoder** [comment]
This repository is just a fork (very outdated) from [BlastEm](https://www.retrodev.com/blastem/) emulator made by Mike Pavone.

Actual development is here: https://www.retrodev.com/repos/blastem
